-- Hand-written migration (NOT auto-generated by `prisma migrate dev`).
-- The auto-diff cannot safely add NOT NULL columns to a populated table, and
-- this backend's schema.prisma intentionally omits several tables/columns
-- owned by the separate YapLin_Admin app (Business.deletedAt, User.email
-- conflict/originalEmail, AdminUser, AuditLog FKs, etc.) — those must NEVER
-- be touched from here, so this migration only contains statements relevant
-- to the GENERAL-pool / event-sourcing / intent-audit feature.

-- ============================================================
-- (a) Transaction.businessId — add nullable, backfill from Store, NOT NULL, FK
-- ============================================================
ALTER TABLE "Transaction" ADD COLUMN "businessId" TEXT;

UPDATE "Transaction" t
SET "businessId" = s."businessId"
FROM "Store" s
WHERE t."storeId" = s.id;

ALTER TABLE "Transaction" ALTER COLUMN "businessId" SET NOT NULL;

ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_businessId_fkey"
  FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ============================================================
-- (b) Transaction.originalAmount — add nullable, backfill = amount, NOT NULL
-- ============================================================
ALTER TABLE "Transaction" ADD COLUMN "originalAmount" DECIMAL(10,2);

UPDATE "Transaction" SET "originalAmount" = "amount";

ALTER TABLE "Transaction" ALTER COLUMN "originalAmount" SET NOT NULL;

-- ============================================================
-- (c) Transaction.storeId — drop RESTRICT fkey, make nullable, re-add as SET NULL
-- ============================================================
ALTER TABLE "Transaction" DROP CONSTRAINT "Transaction_storeId_fkey";

ALTER TABLE "Transaction" ALTER COLUMN "storeId" DROP NOT NULL;

ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_storeId_fkey"
  FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================
-- (d) New enums + cast Transaction.status from text to TransactionStatus
-- ============================================================
CREATE TYPE "TransactionStatus" AS ENUM ('confirmed', 'voided');
CREATE TYPE "TransactionSource" AS ENUM ('auto', 'manual');
CREATE TYPE "TransactionEventType" AS ENUM ('CAPTURED', 'MANUAL_CREATED', 'ASSIGNED', 'RETURNED_TO_GENERAL', 'AMOUNT_CORRECTED', 'VOIDED', 'VOID_REVERSED', 'NOTE_ADDED');
CREATE TYPE "RiskLevel" AS ENUM ('normal', 'watch', 'suspicious', 'blocked');
CREATE TYPE "IntentSeverity" AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE "IntentEventType" AS ENUM ('LOGIN_FAILED', 'BLOCKED_STORE_ACCESS', 'BLOCKED_ROLE_ACTION', 'WRONG_CONFIRMATION', 'RISK_ESCALATED', 'ACCOUNT_AUTO_BLOCKED');

-- Existing rows are all "confirmed" today, which maps directly onto the enum.
ALTER TABLE "Transaction" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Transaction" ALTER COLUMN "status" TYPE "TransactionStatus" USING ("status"::"TransactionStatus");
ALTER TABLE "Transaction" ALTER COLUMN "status" SET DEFAULT 'confirmed';

-- ============================================================
-- (e) Transaction.source / Transaction.version
-- ============================================================
ALTER TABLE "Transaction" ADD COLUMN "source" "TransactionSource" NOT NULL DEFAULT 'auto';
ALTER TABLE "Transaction" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;

-- ============================================================
-- (f) TransactionEvent — new append-only table
-- ============================================================
CREATE TABLE "TransactionEvent" (
    "seq" BIGSERIAL NOT NULL,
    "id" TEXT NOT NULL,
    "transactionId" TEXT NOT NULL,
    "type" "TransactionEventType" NOT NULL,
    "payload" JSONB,
    "actorId" TEXT,
    "actorName" TEXT NOT NULL,
    "actorRole" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TransactionEvent_pkey" PRIMARY KEY ("seq")
);

CREATE UNIQUE INDEX "TransactionEvent_id_key" ON "TransactionEvent"("id");
CREATE INDEX "TransactionEvent_transactionId_seq_idx" ON "TransactionEvent"("transactionId", "seq");

ALTER TABLE "TransactionEvent" ADD CONSTRAINT "TransactionEvent_transactionId_fkey"
  FOREIGN KEY ("transactionId") REFERENCES "Transaction"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ============================================================
-- (g) User.riskLevel / User.transactionPinHash, Business.autoBlockEnabled
-- ============================================================
ALTER TABLE "User" ADD COLUMN "riskLevel" "RiskLevel" NOT NULL DEFAULT 'normal';
ALTER TABLE "User" ADD COLUMN "transactionPinHash" TEXT;

ALTER TABLE "Business" ADD COLUMN "autoBlockEnabled" BOOLEAN NOT NULL DEFAULT false;

-- ============================================================
-- (h) IntentAuditLog — new table, own to this backend (not the shared AuditLog)
-- ============================================================
CREATE TABLE "IntentAuditLog" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "businessId" TEXT NOT NULL,
    "userId" TEXT,
    "actorEmail" TEXT NOT NULL,
    "eventType" "IntentEventType" NOT NULL,
    "severity" "IntentSeverity" NOT NULL,
    "detail" JSONB,
    "ipAddress" TEXT,
    "userAgent" TEXT,

    CONSTRAINT "IntentAuditLog_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "IntentAuditLog" ADD CONSTRAINT "IntentAuditLog_businessId_fkey"
  FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE INDEX "IntentAuditLog_businessId_userId_eventType_createdAt_idx" ON "IntentAuditLog"("businessId", "userId", "eventType", "createdAt");

-- ============================================================
-- (i) Remaining Transaction indexes
-- ============================================================
CREATE INDEX "Transaction_businessId_timestamp_idx" ON "Transaction"("businessId", "timestamp");
CREATE INDEX "Transaction_businessId_storeId_timestamp_idx" ON "Transaction"("businessId", "storeId", "timestamp");
CREATE INDEX "Transaction_storeId_timestamp_idx" ON "Transaction"("storeId", "timestamp");
